server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/globus?WriteBatchedInsert=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25

auth:
  url: "http://127.0.0.1:85/api/v1/auth/"